

-- CREATE PERSON_DETAILS TABLE
CREATE TABLE PERSON_DETAILS
(
    PERSON_ID VARCHAR(200) PRIMARY KEY NOT NULL,
    PERSON_FIRSTNAME VARCHAR(200),
    PERSON_LASTNAME VARCHAR(200),
    PERSON_JOINED_DATE DATE,
    PERSON_GENDER VARCHAR(20),
    STATE VARCHAR(200),
    COUNTRY VARCHAR(200),
    PERSON_ADDRESS VARCHAR(500),
    EMAIL_ADDRESS VARCHAR(200),
    PINCODE VARCHAR(20),
    CONTACT_NUMBER VARCHAR(200),
    NOMINEE VARCHAR(200),
    NOMINEE_RELATION VARCHAR(20),
    PERSON_PASSWORD VARCHAR(200),
    PARENT_REFERENCE VARCHAR(200)
);


-- CREATE TEACHER TABLE
CREATE TABLE TEACHER
(
    TEACHER_ID VARCHAR(200) PRIMARY KEY NOT NULL,
    TEACHER_NAME VARCHAR(200),
    TEACHER_CONTACT_NUMBER VARCHAR(200),
    TEACHER_BDATE DATE,
    TEACHER_ADDRESS VARCHAR(500)
);

-- CREATE STUDENT_SUBJECT_DETAIL TABLE
CREATE TABLE STUDENT_SUBJECT_DETAIL
(
    STUDENT_ID VARCHAR(200),
	STUDENT_SUBJECT VARCHAR(200),
	TEACHER_ID VARCHAR(200),
	TEACHER_NAME VARCHAR(200)

);

CREATE TABLE SUBJECT
(
    SUBJECT_ID VARCHAR(200) PRIMARY KEY NOT NULL ,
	SUBJECT_NAME VARCHAR(200) UNIQUE

);

-- DROP TABLE
use PersonWelfare_V1

DROP TABLE PERSON_DETAILS
 DROP TABLE TEACHER 
DROP TABLE STUDENT_SUBJECT_DETAIL
DROP TABLE SUBJECT